### ISSUE TITLE
error trying to use the package

### ISSUE THREAD

**Issue by matiazar** [kitloong/laravel-migrations-generator#103]
I got this error after executed the package

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'LEVEL' in 'where clause' (SQL: SELECT * FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS
            WHERE TABLE_NAME = 'failed_jobs'
                AND CONSTRAINT_SCHEMA = 'staging_scanner'
                AND LEVEL = 'Column'
                AND CHECK_CLAUSE LIKE '%json_valid(`payload`)%')

**Comment by kitloong** [comment]
Hi @matiazar 

Thank you for reporting, could you please provide the following information:

1. Type of DB:
2. DB version:
3. Laravel framework version:
4. PHP version:
5. Laravel Migrations Generator version:

**Comment by matiazar** [comment]
> Hi @matiazar
> 
> Thank you for reporting, could you please provide the following information:
> 
> 1. Type of DB: MariaDB
> 2. DB version: MariaDB version 10.3.28 
> 3. Laravel framework version: Laravel Framework 8.83.18
> 4. PHP version: PHP 7.4.8
> 5. Laravel Migrations Generator version: 6.3

thanks for answering me

**Comment by kitloong** [comment]
MariaDB Check Constraint https://mariadb.com/kb/en/information-schema-check_constraints-table/

**Comment by matiazar** [comment]
Thanks 4 answering me... I will call server support to upgrade MariaDB version and then confirm you that everything is ok.
