### ISSUE TITLE
What about a data option?

### ISSUE THREAD

**Issue by wiklog** [kitloong/laravel-migrations-generator#11]
First of all, you made a great work!
What about a data option? The idea is to add a -d option that permit to generate a migation file with the data present in the table. A suggest wpuld be:
```
    public function up()
    {
        Schema::create('myTable', function (Blueprint $table) {
            $table->id();
            // others fields
        });

        $data = [
            ["id" => 1, "field_1" => "value_1", /* ...*/  "type" => "field_n" => "value_n"],
            ["id" => 2, "field_1" => "value_1", /* ...*/  "type" => "field_n" => "value_n"],
            /*...*/
            ["id" => n, "field_1" => "value_1", /* ...*/  "type" => "field_n" => "value_n"]
        ];
        DB::table('myTable')->insert($data);
    }
```
I hope you think it's an interesting idea

**Comment by kitloong** [comment]
Hello @wiklog , thank you for feedback.

Your idea is interesting, however I came across this after a quick search:
Inverse seed generator: https://github.com/orangehill/iseed

The package is still maintaining and up to date. 
I think it is better to use seeder generator separately than create an option to do the same thing.

**Comment by wiklog** [comment]
You're right
Thank you for the the link
