### ISSUE TITLE
PostgreSQL add migration to create domains

### ISSUE THREAD

**Issue by EmptySpace99** [kitloong/laravel-migrations-generator#117]
Imagine this scenario in a PostgreSQL db: 

1) Create a domain: ``` create domain word64 as varchar(64); ```
2) Create the following table:
 ``` 
CREATE TABLE cars (
   id serial PRIMARY KEY,
   name word64 NOT null
);
```
3) Run the command: ``` php artisan migrate:generate ```

4) Migration created: 
```
Schema::create('cars', function (Blueprint $table) {
  $table->increments('id');
});
DB::statement("ALTER TABLE cars ADD name word64 NOT NULL");
```

Obviously if you try to execute this migration you will get an error cause postgres can't recognize the word64 type. I would like that the command ``` php artisan migrate:generate ``` generate another migration to specify the domains created previously.

**Comment by kitloong** [comment]
Hi @EmptySpace99, thanks for reporting the issue.

I like the idea of `create type`. However, I need more time to research and implement this feature due to my tight schedule.
Please feel free to push PR, or any `SQL statement` that you think will be helpful for development.
