### ISSUE TITLE
Issue with Laravel 5.6

### ISSUE THREAD

**Issue by shahidkarimi** [kitloong/laravel-migrations-generator#119]
When run generate command gives this error:

`Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to KitLoong\MigrationsGenerator\Setting::setTableFilename() must be of the type string, null given, called in /home/my_project/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php on line 144

  at /home/my_project/vendor/kitloong/laravel-migrations-generator/src/Setting.php:170
    166| 
    167|     /**
    168|      * @param  string  $tableFilename
    169|      */
  > 170|     public function setTableFilename(string $tableFilename): void
    171|     {
    172|         $this->tableFilename = $tableFilename;
    173|     }
    174| 

  Exception trace:

  1   KitLoong\MigrationsGenerator\Setting::setTableFilename()
      /home/my_project/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php:144

  2   KitLoong\MigrationsGenerator\MigrateGenerateCommand::setup()
      /home/my_project/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php:84

  Please use the argument -v to see more details.`

**Comment by kitloong** [comment]
Hi @shahidkarimi Thanks for reporting the issue.

I am sorry for my late reply. I am currently away and will be available by the end of this month. 

I will have a check this issue as soon as possible.

**Comment by kitloong** [comment]
Hi @shahidkarimi , could you please check #67 ?

If the above fail to resolve your issue, kindly provide your `composer.json` for investigation purpose.

**Comment by kitloong** [comment]
I will close this issue for now.
Feel free to reopen this issue if you have more details to share.
