### ISSUE TITLE
local.ERROR: Undefined array key "level"

### ISSUE THREAD

**Issue by ahmadfds** [kitloong/laravel-migrations-generator#121]
Hello, 

I'm using laravel 9 + mariadb 10.5.8, when I tried to genrate the migration file form the database I've got this error, looks that the returned constraints doesn't have "level" key, check the line in bold

> [2022-10-01 08:44:07] local.ERROR: Undefined array key "level" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"level\" at /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1679)
> [stacktrace]
> #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
> #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1679): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
> **#2 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/Repositories/Entities/MariaDB/CheckConstraint.php(47): Illuminate\\Support\\Collection->offsetGet()**
> #3 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/Repositories/MariaDBRepository.php(29): KitLoong\\MigrationsGenerator\\Repositories\\Entities\\MariaDB\\CheckConstraint->__construct()
> #4 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/DBAL/Models/MySQL/MySQLColumn.php(161): KitLoong\\MigrationsGenerator\\Repositories\\MariaDBRepository->getCheckConstraintForJson()
> #5 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/DBAL/Models/MySQL/MySQLColumn.php(61): KitLoong\\MigrationsGenerator\\DBAL\\Models\\MySQL\\MySQLColumn->isJson()
> #6 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/DBAL/Models/DBALColumn.php(128): KitLoong\\MigrationsGenerator\\DBAL\\Models\\MySQL\\MySQLColumn->handle()
> #7 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/DBAL/Models/MySQL/MySQLTable.php(26): KitLoong\\MigrationsGenerator\\DBAL\\Models\\DBALColumn->__construct()
> #8 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/DBAL/Models/DBALTable.php(56): KitLoong\\MigrationsGenerator\\DBAL\\Models\\MySQL\\MySQLTable->makeColumn()
> #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(758): KitLoong\\MigrationsGenerator\\DBAL\\Models\\DBALTable->KitLoong\\MigrationsGenerator\\DBAL\\Models\\{closure}()
> #10 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/DBAL/Models/DBALTable.php(59): Illuminate\\Support\\Collection->reduce()
> #11 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/DBAL/MySQLSchema.php(25): KitLoong\\MigrationsGenerator\\DBAL\\Models\\DBALTable->__construct()
> #12 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php(392): KitLoong\\MigrationsGenerator\\DBAL\\MySQLSchema->getTable()
> #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(262): KitLoong\\MigrationsGenerator\\MigrateGenerateCommand->KitLoong\\MigrationsGenerator\\{closure}()
> #14 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php(396): Illuminate\\Support\\Collection->each()
> #15 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php(345): KitLoong\\MigrationsGenerator\\MigrateGenerateCommand->generateTablesToTemp()
> #16 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php(306): KitLoong\\MigrationsGenerator\\MigrateGenerateCommand->generateSquashedMigrations()
> #17 /var/www/html/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php(102): KitLoong\\MigrationsGenerator\\MigrateGenerateCommand->generate()
> #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): KitLoong\\MigrationsGenerator\\MigrateGenerateCommand->handle()
> #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
> #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
> #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
> #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\\Container\\Container->call()
> #24 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
> #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\\Component\\Console\\Command\\Command->run()
> #26 /var/www/html/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run()
> #27 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
> #28 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
> #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
> #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(151): Illuminate\\Console\\Application->run()
> #31 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
> #32 {main}
> "}
>

**Comment by kitloong** [comment]
Hi @ahmadfds 

Thanks for reporting.
Could you please provide the migration generator version number?

**Comment by ahmadfds** [comment]
It's 6.4.1

**Comment by kitloong** [comment]
Relates to #103

**Comment by kitloong** [comment]
Fixed and released with tag `v6.4.2`
