### ISSUE TITLE
Migrations: merged different table (on different schema) that have same name

### ISSUE THREAD

**Issue by luca-rigutti** [kitloong/laravel-migrations-generator#126]
**Describe the bug**
The migration generated from a database that has multiple schema, with inside a table with same name (e.g. schema1.tablea and schema2.tablea) get all the columns and mixed toghether.

**To Reproduce**
1. Create schema test1 and test2
2. Create a table inside each schema with same name, but different parameter
3. Run `php artisan migrate:generate ...`
5. See the migration created, with the both columns of all table

**Expected behavior**
The possibility that I think I want are two: generate a schema for each table of schemas (so using prefix of schema) or to use only the default (or selected on config file).
For me the better is the first, so I can have all the migrations correct.

**Details (please complete the following information):**
 - DB: postgres
 - DB Version: 14.2-1 with docker
 - Laravel Version: v9.35.1
 - PHP Version: PHP 8.1.11
 - Migrations Generator Version: v6.4.3

**Comment by kitloong** [comment]
https://github.com/doctrine/dbal/pull/5765

**Comment by kitloong** [comment]
Confirm fixed with https://github.com/doctrine/dbal/pull/5765.
Please upgrade `doctrine/dbal:^3.4.6`
