### ISSUE TITLE
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in Container.php:805

### ISSUE THREAD

**Issue by marcosdsdba** [kitloong/laravel-migrations-generator#13]
After composer install when run php artisan:migrate returns error :

PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in Container.php:805

Laravel 7 (current version Jun - 2020)

Composer 1.10.7

**Comment by kitloong** [comment]
Hello @marcosdsdba 

I have tested migration generator in fresh Laravel 7 however I can't repro your issue.

Migration Generator: v4.4.0
Laravel: v7.17.2

Please retry after following steps:
1. Delete cache files in `bootstrap/cache`
1. Run `composer dump-autoload`

**Comment by marcosdsdba** [comment]
I have a Vagrant LEMP VM (NginX, Mysql 8 and PHP7.3) with composer 1.10.8(upgrade today to 8). I downgraded Laravel from 7 to 6 and it worked.
Thank you.
