### ISSUE TITLE
Error in Laravel-Zero

### ISSUE THREAD

**Issue by gpibarra** [kitloong/laravel-migrations-generator#130]
**Describe the bug**
I have installed the library together with LaravelZero.
When adding the serverProvider an error appears in the `registerConfig()` function: `Target class [files] does not exist.`

**To Reproduce**
```sh
composer create-project --prefer-dist laravel-zero/laravel-zero laravel-zero-migrations-generator
cd laravel-zero-migrations-generator
php application app:install database
# add 'KitLoong\MigrationsGenerator\MigrationsGeneratorServiceProvider::class' to array 'providers' in file 'config/app.php'
php application migrate:generate
````

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - DB: MariaDb
 - DB Version: 15.1
 - Laravel-Zero Version: 9.26.1
 - PHP Version: 8.1.0
 - Migrations Generator Version: 6.4.3

**Additional context**

**Comment by kitloong** [comment]
Released with tag `v6.6.0`.
