### ISSUE TITLE
[Feature] Support Custom Types DBA

### ISSUE THREAD

**Issue by gpibarra** [kitloong/laravel-migrations-generator#133]
In my Database (MSSQL) i have a custom type, so the execution fails
```sql
CREATE TYPE [dbo].[AccountNumber] FROM [nvarchar](15) NULL
```

```sh
 Doctrine\DBAL\Exception 

  Unknown database type name requested, Doctrine\DBAL\Platforms\SQLServer2012Platform may not support it. 
```

** References
[https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/cookbook/custom-mapping-types.html](https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/cookbook/custom-mapping-types.html)
[https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/cookbook/advanced-field-value-conversion-using-custom-mapping-types.html#advanced-field-value-conversion-using-custom-mapping-types](https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/cookbook/advanced-field-value-conversion-using-custom-mapping-types.html#advanced-field-value-conversion-using-custom-mapping-types)

**Comment by kitloong** [comment]
@gpibarra Thanks for reporting.

I have implemented a similar feature for PgSQL, I will handle this issue.
