### ISSUE TITLE
Issue running on SQL Server

### ISSUE THREAD

**Issue by rotunomp** [kitloong/laravel-migrations-generator#137]
Hello, I am running this for the first time on a SQL Server connection and I am getting the below error. I was able to get it working on a local postgres DB, but not the SQL Server connection. 

[PDOException (HY093)]                                                                    
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

 - DB: SQL Server 2019
 - Laravel Version: 8.75.0
 - PHP Version: 8.1.9
 - Migrations Generator Version: 6.5.1
 - Doctrine DBAL Version [`doctrine/dbal`]: 3.5.1

### Stack Trace:

```
  at /vendor/doctrine/dbal/src/Driver/PDO/Statement.php:134

 PDOStatement->execute() at /vendor/doctrine/dbal/src/Driver/PDO/Statement.php:134

 Doctrine\DBAL\Driver\PDO\Statement->execute() at /vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php:69

 Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware->execute() at /vendor/doctrine/dbal/src/Connection.php:1063

 Doctrine\DBAL\Connection->executeQuery() at /vendor/doctrine/dbal/src/Schema/SQLServerSchemaManager.php:406

 Doctrine\DBAL\Schema\SQLServerSchemaManager->selectTableNames() at /vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:356

 Doctrine\DBAL\Schema\AbstractSchemaManager->doListTableNames() at /vendor/doctrine/dbal/src/Schema/SQLServerSchemaManager.php:40

 Doctrine\DBAL\Schema\SQLServerSchemaManager->listTableNames() at /vendor/kitloong/laravel-migrations-generator/src/DBAL/DBALSchema.php:33

 KitLoong\MigrationsGenerator\DBAL\DBALSchema->getTableNames() at /vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php:185

 KitLoong\MigrationsGenerator\MigrateGenerateCommand->filterTables() at /vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php:110

 KitLoong\MigrationsGenerator\MigrateGenerateCommand->handle() at /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
```

**Comment by kitloong** [comment]
Hi @rotunomp , thank you for reporting this issue.

Looks like the error is caused by 

```
Doctrine\DBAL\Schema\SQLServerSchemaManager->selectTableNames() at /vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:356

Doctrine\DBAL\Schema\AbstractSchemaManager->doListTableNames() at /vendor/doctrine/dbal/src/Schema/SQLServerSchemaManager.php:40
```

Do you able to find any related issues in `doctrine/dbal` ?
If you believe this is a bug, you could raise a PR to `doctrine/dbal`.

**Comment by rotunomp** [comment]
Sorry for the late response, thank you for replying to this issue.

I opened a bug report with DBAL over here:

https://github.com/doctrine/dbal/issues/5816

I took quite some time to replicate the issue without the Laravel DB facade but couldn't get it to work. I figure the devs over at dbal are going to ask me to try without Laravel and just using the regular php sqlsrv connection. So we'll see what they say.

**Comment by rotunomp** [comment]
Wanted to give some closure on this. I spent far too much time trying to set up an SQL Server connection from scratch as opposed to using Laravel. I can't believe how hard it is! It ended up never working and I don't have the time at my job to mess around with it more, unfortunately. I think I'll have to find another way to make the migrations :(

**Comment by kitloong** [comment]
@rotunomp I am sorry to hear this.

Could you share the schema and steps to repro issue at here? With Laravel is fine.

**Comment by rotunomp** [comment]
Thank you for your time. I can give you a rundown of our stack. I did just realize that our company is not using the Microsoft ODBC, but FreeTDS instead. I am attempting to set up a version on my local environment using ODBC to see if the same issue will happen.

```
OS: Amazon Linux 2
Database: SQL Server 2019
PHP: 8.1.9
Laravel:  9.39.0
FreeTDS: 1.3.3
```

Here's an example table which does not work:
```
CREATE TABLE [dbo].[account_types] (
    [account_type_id] varchar(2),
    [account_type_name] varchar(100)
);
```

Here is the database.php entry for the sqlsrv connection:

```
        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'options' => [
                PDO::ATTR_TIMEOUT => 300,
            ],
        ],
```

I am running `php artisan migrate:generate --tables="account_types"`

**Comment by kitloong** [comment]
I am glad to hear that

**Comment by rotunomp** [comment]
@Sammyjo20 is ODBC required for Azure SQL Edge? If so have you already installed it? For SQL Server at least, I wouldn't be able to make the Laravel DB connection work without ODBC.

I'm running an Intel Macbook so I don't have any specific instructions for M1, although this is the guide I used to setup ODBC on my Mac:

https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver16

I used Version 17 instead of 18 of the ODBC because version 18 had something involving encryption that I didn't understand. But our SQL Server instance might be configured differently than yours because ours has been around for a very long time.

**Comment by Sammyjo20** [comment]
Thanks so much for the help!

**Comment by rw152** [comment]
I modified ```vendor/doctrine/dbal/src/Connection@executeQuery``` and set 

```php
$params=[];
```
on line 1081 (approximately) and it seemed to work.

![image](https://user-images.githubusercontent.com/5873535/231528652-dee3e3f3-b0de-4dee-9653-33d7cab41607.png)


My thought is when DBAL attempts to run the ```selectTableNames``` method in ```vendor/doctrine/dbal/src/Schema/SQLServerSchemaManager@selectTableNames``` it passes in a parameter (in my case, the DB name). The executed statement, however, should not have a parameter and thus too many are passed in.

![image](https://user-images.githubusercontent.com/5873535/231529429-031352f6-70bc-4b90-b88e-40a2a9dc0381.png)

I didn't dig any further than that, but setting that parameter to an empty array patched it for now.
