### ISSUE TITLE
Does not respect Laravel 7 stub customization

### ISSUE THREAD

**Issue by maarten00** [kitloong/laravel-migrations-generator#14]
This package is awesome, it has saved me a lot of time. I've found a way to make it even better;

I've customized my stubs using Stub Customization: https://laravel.com/docs/7.x/artisan#stub-customization
I noticed that this package seems to ignore my customized stubs. 

It would be amazing if this feature could be supported.

**Comment by kitloong** [comment]
Hello @maarten00 ,
Thank you, that would be an interesting feature. 

While I will look into it, PR from you is more than welcome too.

**Comment by kitloong** [comment]
Hi @maarten00 

I have tried to recognize `migration.stub` from `stub:publish` and here is the default content I got:
```
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
```

While it is possible to replace `//` with the generated content however it is too risky and fragile to treat `//` as placeholder.

In the meantime, if you need to use your custom stub, you could always utilize option `--template-path`, which accept any of your template path for the migration stub.

I am closing this issue for now.
If you have a better idea please leave a comment or create a pull request!
