### ISSUE TITLE
generate migrations for a connection but skip connection name into output

### ISSUE THREAD

**Issue by scramatte** [kitloong/laravel-migrations-generator#145]
Hi,

I need generate migrations for a specific connection but skip connection name into output.
How can I achieve it?

Regards

**Comment by kitloong** [comment]
Hi @scramatte , to output with the default connection, you can temporarily set your default connection to the specific connection you wish to generate.

For instance,

```
DB_CONNECTION=specific_connection php artisan migrate:generate
```
