### ISSUE TITLE
Is there any way of sync the database to the migrations

### ISSUE THREAD

**Issue by Samuel-Bie** [kitloong/laravel-migrations-generator#15]
This is not an issue.

I want to know, if its possible thru this package to sync my migration or generate new migrations when i add or remove (colomn or row of  table)  in the database?

**Comment by kitloong** [comment]
Hello @Samuel-Bie 

Unfortunately, I don't think this package can handle this.
You need to write your alter in migration, and migrate thru
```
php artisan migrate
```

**Comment by Samuel-Bie** [comment]
Hi @kitloong  writting alter migration is what i want to avoid doing. But Any way its a great pkage
