### ISSUE TITLE
php-enum  version incompatible

### ISSUE THREAD

**Issue by zc520yzy** [kitloong/laravel-migrations-generator#151]
myclabs/php-enum  1.6 not compatible 6.6，You need to make changes in composer.json， thnks

**Comment by kitloong** [comment]
Hi @zc520yzy , thanks for reporting.

This issue was raised and fixed at here #147 .
If you think the issue is not resolved yet, please provide more details and steps to repro

**Comment by zc520yzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zc520yzy** [comment]
"kitloong/laravel-migrations-generator": "^6.7",

**Comment by zc520yzy** [comment]
The execution of laravel-migrations-generator 6.7 and myclabs/php-enum 1.6 will throw an exception；
![image](https://user-images.githubusercontent.com/19699252/209596629-d4ffabab-e382-4c4e-af30-197b3203dc64.png)

**Comment by kitloong** [comment]
Thank you @zc520yzy . This issue has been fixed with tag `v6.7.1`.
