### ISSUE TITLE
Full Text Index not recognised

### ISSUE THREAD

**Issue by cannycookie** [kitloong/laravel-migrations-generator#16]
Great module, really useful thank you.  

A Full Text index though is created as a regular index which throws an error when trying to index a TEXT field

Not sure if laravel has a method so I normally create a direct command to make them:-

`DB::statement('ALTER TABLE `faqs` ADD FULLTEXT `full_text` (`question`, `answer`);');`

**Comment by kitloong** [comment]
I think Laravel does not provide FULLTEXT migration method.

The solution would be as you suggested, direct command by `DB::statement()`

I need to check if this is doable via generator.

**Comment by kitloong** [comment]
@cannycookie You may already know, in Laravel 8 we will have 
```
# dump the current state of your schema to a database/schema/{connection}-schema.mysql file
php artisan schema:dump
```

https://laravel-news.com/schema-dump

**Comment by cannycookie** [comment]
Great, thanks, that could be useful 👍
