### ISSUE TITLE
Multiple Primary Keys defined

### ISSUE THREAD

**Issue by Pimmeul** [kitloong/laravel-migrations-generator#160]
**Describe the bug**
migration is generated with an $table->integer('xx', true) // autoIncrement which laravel sees as a primary key.
if the table also consists of constraint primary key it will throw an error because there is already an primary key set. 

**To Reproduce**
1. Create table '...'
2. add a integer column with autoincrement
3. add $table->primary(['columname]);
4. Run `php artisan migrate:generate ...`
5. See error

**Expected behavior**
remove autoincrement so there is not a primary key before the constraint

**Screenshots**
<img width="898" alt="afbeelding" src="https://user-images.githubusercontent.com/55128050/218861658-aa2b0cd0-f477-4a5a-b5af-b1e6738a2331.png">

<img width="590" alt="afbeelding" src="https://user-images.githubusercontent.com/55128050/218862299-a96420d1-d607-4320-9ddf-cd63b328991d.png">

**Details (please complete the following information):**
 - DB: MariaDB
 - DB 10.7
 - Laravel Version: 9
 - PHP Version: 8.2.1
 - Migrations Generator Version: 6.8
 - Doctrine DBAL Version [`doctrine/dbal`]: ?

**Comment by kitloong** [comment]
Hi @Pimmeul Thanks for reporting.

I attempted to fix this previously but didn't have a good solution then.
Let me look into this again.

**Comment by kitloong** [comment]
Hi @Pimmeul 

Following is the way for the feature to work:

```
Schema::create('table', function (Blueprint $table) {
    $table->integer('id', true); // Will create primary key
    $table->integer('field1');
    $table->integer('field2');

    $table->dropPrimary(); // Drop previous key

    $table->primary(['field1', 'field2']); // Recreate primary key
});
```

Laravel migration will create a primary key for you if you define autoincrement.

May I know in what use case you need a autoincrement column without a primary key?

If you have an autoincrement column you should use it as your primary key.

Then create a unique constraint for the other columns.

```
$table->unique(['field1', 'field2']);
```

**Comment by kitloong** [comment]
Will close this issue for now
