### ISSUE TITLE
Inconsistent ordering in squashed migration

### ISSUE THREAD

**Issue by CalebDW** [kitloong/laravel-migrations-generator#167]
**Describe the bug**
Hello!

I'm using this package to generate a dummy (squashed) migration file for Larastan to read since it doesn't support reading Postgres Schema Dumps.

However, I've noticed that if I regenerate the migration file (even when there have not been any schema changes) that a few lines are reordered which necessitates redundant git commits.

**To Reproduce**
1. Create several tables
2. Run `php artisan migrate:generate --table-filename create_tables.php --skip-log --skip-proc --skip-views --squash`
3. Commit changes
4. Re-run command in Step. 2.
5. See changed migration file.

**Expected behavior**
I expect the migration file to remain unchanged when there have not been any schema changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/4176520/226437062-4a5be02a-4c8b-4561-b9cc-31c40f6ef4d6.png)

**Details (please complete the following information):**
 - DB: [e.g. MySQL] Postgres
 - DB Version: [e.g. 5.7.37] 14
 - Laravel Version: 9.X
 - PHP Version: 8.1
 - Migrations Generator Version: 
 - Doctrine DBAL Version [`doctrine/dbal`]:

**Additional context**

**Comment by kitloong** [comment]
@CalebDW Released with tag `v6.9.0`, thank you.
