### ISSUE TITLE
when generating migration i get  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'GENERATION_EXPRESSION' in 'field list' 

### ISSUE THREAD

**Issue by aboui** [kitloong/laravel-migrations-generator#171]
**Describe the bug**

**To Reproduce**

2. Run `php artisan migrate:generate`
3. See error "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'GENERATION_EXPRESSION' in 'field list' "

**Expected behavior**
i expected to generate the migration files in database migration directory

**Screenshots**
![image](https://user-images.githubusercontent.com/46619634/226869541-8c2e0338-3a05-4442-bffb-788fd25aa061.png)

**Details (please complete the following information):**
 - DB: MariaDB
 - DB Version: 10.1.48
 - Laravel Version: 10
 - PHP Version:  8.1
 - Migrations Generator Version: 6

**Additional context**

**Comment by kitloong** [comment]
Hi @aboui, thank you for reporting.

I think this is due to the particular MariaDB version missing that column.

I will investigate this issue, however, I am currently away from my computer. Likely, I will be able to fix it on next week.

**Comment by kitloong** [comment]
Thank you @aboui. The fix has been released with the tag `v6.9.1`.

**Comment by aboui** [comment]
You welcome 👍🙂

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
