### ISSUE TITLE
Argument 1 passed to KitLoong\MigrationsGenerator\Setting::setPath() must be of the type string

### ISSUE THREAD

**Issue by KonstantinKorepin** [kitloong/laravel-migrations-generator#184]
Hello!

When I run the command `php artisan migrate:generate` I get a message "Argument 1 passed to KitLoong\MigrationsGenerator\Setting::setPath() must be of the type string, null given, called in /home/kostya/server/regop.local/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php on line 155"

Then I run `php artisan migrate:generate --path=/app/database/migrations ` and I get Message
" Argument 1 passed to KitLoong\MigrationsGenerator\Setting::setStubPath() must be of the type string, null given, called in /home/kostya/server/regop.local/vendor/kitloong/laravel-migrations-generator/src/MigrateGenerateCommand.php on line 193"

Why is this happening? What am I doing wrong? I want the migrations to go to the default folder `database/migrations`

**Details:**
 - DB: PostgreSQL
 - DB Version: [15.3 (Ubuntu 15.3-1.pgdg22.04+1)]
 - Laravel Version: 7.22.4
 - PHP Version: 7.3.33-10+ubuntu22.04.1+deb.sury.org+1
 - Migrations Generator Version: 6.1.0
 - Doctrine DBAL Version [`composer info doctrine/dbal | grep versions`]: 2.10.2

**Comment by kitloong** [comment]
Hi @KonstantinKorepin I am sorry for being late.

Could you please try Migration Generator latest version `6.10.0`?

I have no issue with `php artisan migrate:generate --path=/app/database/migrations`.

Just FYI, you should use `app/` instead of `/app/` to output to relative path.

**Comment by KonstantinKorepin** [comment]
Hi @kitloong !

Thank you very much! It's works!
