### ISSUE TITLE
Run from Controller

### ISSUE THREAD

**Issue by Jhon-Marulanda** [kitloong/laravel-migrations-generator#190]
Hello! Can I execute the command php artisan migrate:generate from some controller or trait? I need to be able to do it from the code and not from console, thanks (Laravel 10).

**Comment by kitloong** [comment]
Hi @Jhon-Marulanda , you could run `Artisan::command('migrate:generate')` from your controller, I think it should work.

Reference: https://laravel.com/docs/10.x/artisan#closure-commands

**Comment by kitloong** [comment]
Hi @Jhon-Marulanda I am sorry for being late. May I know if your issue has been resolved?
