### ISSUE TITLE
Custom postgres types fails if there is an index on the type

### ISSUE THREAD

**Issue by esbenp** [kitloong/laravel-migrations-generator#198]
**Describe the bug**

#107 added support for custom postgres types. The problem is the type is added outside of the normal migration, which is a problem if said column is also in an index on the table

**To Reproduce**

1. Create table with column that is a type, but which also has an index on that column
2. Generate migrations

This will create a migration ala

```
public function up()
{
    Schema::create('table', function (Blueprint $table) {
        ...

        $table->index(['column']);
    });
    DB::statement("ALTER TABLE table ADD column custom_type NOT NULL");
}
```

Which will fail since `column` is not defined when the index is added

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - DB: Postgresql
 - DB Version: 10+
 - Laravel Version: 10 
 - PHP Version: 8.3
 - Migrations Generator Version: 6.11
 - Doctrine DBAL Version [`composer info doctrine/dbal | grep versions`]: 3.7.2

**Additional context**

**Comment by esbenp** [comment]
Correction: I think this only happens if it's part of a composite index

**Comment by kitloong** [comment]
@esbenp Thank you for raising the issue.

I was finally able to fix this after a while, sorry for taking for a while.

**Comment by esbenp** [comment]
Thanks!
