### ISSUE TITLE
Undefined property: stdClass::$column_name

### ISSUE THREAD

**Issue by JeffreyBool** [kitloong/laravel-migrations-generator#2]
![image](https://user-images.githubusercontent.com/24415888/77616565-ed809700-6f6c-11ea-8196-1ab9c65a6b60.png)

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/77617110-4a308180-6f6e-11ea-8bac-623b733fec7f.png)
改成大写就行了

**Comment by kitloong** [comment]
Thank you for report
谢谢
