### ISSUE TITLE
Option for single file generation

### ISSUE THREAD

**Issue by miken32** [kitloong/laravel-migrations-generator#20]
Would love to see an option for generating a single file with all migration data. One file per table, and another for foreign keys, is a lot of files!

**Comment by djvickx** [comment]
Any update on it? When can we have this feature?

**Comment by acidjazz** [comment]
Took a crack at this with #25 , it ain't pretty but its working! @miken32 @kitloong @djvickx

**Comment by kitloong** [comment]
Thank you @acidjazz 

This feature has been released in `v.5.0.0`
