### ISSUE TITLE
Cannot generate migration for MariaDB connection

### ISSUE THREAD

**Issue by mocfaisal** [kitloong/laravel-migrations-generator#218]
**Describe the bug**
I can't generate migration for MariaDB connection from current database

**To Reproduce**
1. Run `php artisan migrate:generate`
2. Run `php artisan migrate:generate --connection="mariadb"`
3. See error

**Expected behavior**
Can generate migration for MariaDB connection

**Screenshots**
![image](https://github.com/kitloong/laravel-migrations-generator/assets/27264641/32a3cd12-5ddd-42da-b176-24e84965582d)

**Details (please complete the following information):**
 - DB: MariaDB
 - DB Version: 11.3.2
 - Laravel Version: 11.9.1
 - PHP Version: 8.3.7
 - Migrations Generator Version: 7.0.2

**Additional context**
because generating for mariadb connection error, i tried to generate for mysql connection and success

**Comment by kitloong** [comment]
Hi @mocfaisal, thanks for the report.

I have add the missing `mariadb` driver to compatible with Laravel v11, released with tag `7.0.3`.

**Comment by mocfaisal** [comment]
@kitloong Thanks 🔥
