### ISSUE TITLE
Collation and charset for columns and tables

### ISSUE THREAD

**Issue by nick15marketing** [kitloong/laravel-migrations-generator#23]
Would be good to have the option specifying collation and charsets in migrations for DB's that support it eg MySQL. Ideally both at table and column level.

**Comment by kitloong** [comment]
You should define collation in your `config/database.php`

https://github.com/laravel/laravel/blob/8.x/config/database.php#L55-L56

Laravel will use `collation` and `charet` in the config when you execute `php artisan migrate`

**Comment by nick15marketing** [comment]
Problem is you may need to specify certain tables to have a different collation and charset to that defined in your config. I've got an issue where the production db has different collation and charset all over the place. When I export this DB and then migrate all tables charset and collation match whats in the config and don't match production which could lead to bugs and inaccurate tests. I've had to use a combination of this [https://github.com/cviebrock/sequel-pro-laravel-export] for creation of new tables as it exports charset/collation and this tool for exporting foreign keys to get an exact copy of production structure.

**Comment by kitloong** [comment]
Thank you @nick15marketing 

If you are refer to generate charset/collation different with the one you set in config, I am currently working on it.
