### ISSUE TITLE
Type of datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP not properly represented by generate command

### ISSUE THREAD

**Issue by moseslecce** [kitloong/laravel-migrations-generator#236]
**Describe the bug**
When running the migrate:generate command the resulting migration code does not include the ON UPDATE value

**To Reproduce**
1. Create table date_test:

```sql
CREATE TABLE `date_test` (
  `id` int NOT NULL AUTO_INCREMENT,
  `updated` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `a_timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

2. Run `php artisan migrate:generate`

3. Open resulting migration file to find the following code:
```php
    public function up(): void
    {
        Schema::create('date_test', function (Blueprint $table) {
            $table->integer('id', true);
            $table->dateTime('updated')->nullable()->useCurrent();
            $table->timestamp('a_timestamp')->useCurrentOnUpdate()->nullable()->useCurrent();
        });
    }
```

**Expected behavior**
I would expect the updated field to include the details about the ON UPDATE CURRENT_TIMESTAMP.  One way to achieve this would be for the 'updated' field to use the following code:

```php
$table->dateTime('updated')->useCurrentOnUpdate()->nullable()->useCurrent();
```

**Details (please complete the following information):**
 - DB: MySQL 
 - DB Version: 8.0.39
 - Laravel Version: 11.9
 - PHP Version:  8.3.6
 - Migrations Generator Version: 7.0.5

**Additional context**
If we look at the code inside the isOnUpdateCurrentTimestamp function from src/Repositories/MySQLRepository.php, it only checks AND Type = 'timestamp', so it will not get the correct results regarding "onUpdateCurrentTimestamp" for datetime fields.

**Comment by kitloong** [comment]
Thank you @moseslecce . This has been fixed and release in `v7.0.6`
