### ISSUE TITLE
Type of DATETIME(2) is not being correctly represented by generate command

### ISSUE THREAD

**Issue by moseslecce** [kitloong/laravel-migrations-generator#237]
**Describe the bug**
When running the migrate:generate command the resulting migration code does not generate the correct code.

**To Reproduce**
1. Create table date_test:

```sql
CREATE TABLE `date_test` (
  `id` int NOT NULL AUTO_INCREMENT,
  `updated_datetime_2` datetime(2) DEFAULT CURRENT_TIMESTAMP(2) ON UPDATE CURRENT_TIMESTAMP(2),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
```

2. Run `php artisan migrate:generate`

3. Open resulting migration file to find the following code:
```php
    public function up(): void
    {
        Schema::create('date_test', function (Blueprint $table) {
            $table->integer('id', true);
            $table->dateTime('updated_datetime_2', 2)->nullable()->default('CURRENT_TIMESTAMP(2)');
        });
    }
```

**Expected behavior**
I would expect the updated_datetime_2 field to use the useCurrentOnUpdate method and the useCurrent() method to achieve the defaults for this field.

```php
$table->dateTime('updated_datetime_2', 2)->nullable()->useCurrent()->useCurrentOnUpdate();
```

**Details (please complete the following information):**
 - DB: MySQL 
 - DB Version: 8.0.39
 - Laravel Version: 11.9
 - PHP Version:  8.3.6
 - Migrations Generator Version: 7.0.5

**Additional context**
The generated code attempts to put everything as a string, into the default function.  This creates a syntax error.

**Comment by kitloong** [comment]
Thank you @moseslecce . This has been fixed and release in `v7.0.6`
