### ISSUE TITLE
There's a way to generate a migration from *.sql file?

### ISSUE THREAD

**Issue by celorodovalho** [kitloong/laravel-migrations-generator#24]
There's a way to generate a migration from *.sql file?

I was reading the documentation, and couldn't an answer for this.
I don't want to generate it from a connection, but from an SQL file, can I do it maybe using one of yours classes?

**Comment by kitloong** [comment]
Hello @celorodovalho 

I am sorry this package does not support generate migration from *.sql file.

As an alternative, you could:
1. Import *.sql file into your Database.
2. Use this package to generate migrations from the connection.
