### ISSUE TITLE
Squash only the foreign key migrations

### ISSUE THREAD

**Issue by forviaAnis** [kitloong/laravel-migrations-generator#243]
Currently, after running the generate command, we get several migrations named "create_x_table" that create tables.
Then after that, we get several migrations called "add_foreign_keys_to_x_table" that add foreign keys.

Is there a way to squash only the foreign keys migrations?
So the result will be: several migrations named "create_x_table", but only one migrations named "add_foreign_keys_to_tables" or similar naming

**Comment by kitloong** [comment]
Hi @forviaAnis , currently there is no way to squash only the foreign key migrations. You would need to combine manually by yourself.
