### ISSUE TITLE
Trying to Generate migration on SQL SERVER EXPRESS 2022

### ISSUE THREAD

**Issue by ejaysaya** [kitloong/laravel-migrations-generator#244]
so here's what i did.

```
php artisan migrate:generate --tables="Laravel_UserInfo"
Using connection: sqlsrv

Generating migrations for: Laravel_UserInfo

 Do you want to log these migrations in the migrations table? (yes/no) [yes]:
 > no

Setting up Tables and Index migrations.

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '('. (Connection: sqlsrv, SQL: select idx.name as name, string_agg(col.name, ',') within group (order by idxcol.key_ordinal) as columns, idx.type_desc as [type], idx.is_unique as [unique], idx.is_primary_key as [primary] from sys.indexes as idx join sys.tables as tbl on idx.object_id = tbl.object_id join sys.schemas as scm on tbl.schema_id = scm.schema_id join sys.index_columns as idxcol on idx.object_id = idxcol.object_id and idx.index_id = idxcol.index_id join sys.columns as col on idxcol.object_id = col.object_id and idxcol.column_id = col.column_id where tbl.name = N'Laravel_UserInfo' and scm.name = schema_name() group by idx.name, idx.type_desc, idx.is_unique, idx.is_primary_key)

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

  1   vendor\laravel\framework\src\Illuminate\Database\Connection.php:412
      PDOException::("SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '('.")

  2   vendor\laravel\framework\src\Illuminate\Database\Connection.php:412
      PDOStatement::execute()
```
![image](https://github.com/user-attachments/assets/8c49948e-3718-4dc8-acfa-2514cd0e44b1)

**Comment by ejaysaya** [comment]
here's the structure of Laravel_UserInfo table

![image](https://github.com/user-attachments/assets/ccc4c696-cc22-4215-aefc-61df2e2f0f2b)

**Comment by kitloong** [comment]
Hi @ejaysaya , thank you for reporting the issue.

Could you provide the sql of `Laravel_UserInfo` so I can better investigate and reproduce error from my side?

**Comment by kitloong** [comment]
Upon my checking, it appears that the SQL originates from the Laravel framework itself. [`compileIndexes`](https://github.com/laravel/framework/blob/7db7ea950d3df663391718730f4490a4e189234a/src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php#L158). 

While laravel-migrations-generator does invoke the framework's builtin method to get table indexes, it seems the error is not related to the generator.

**Comment by ejaysaya** [comment]
here's some screenshot that will give you reference. in the figure below will show you i command **php artisan db:show**

![image](https://github.com/user-attachments/assets/64ab4fa9-5d24-4d58-ad05-7a21aea9abde)

**Comment by ejaysaya** [comment]
and then in this 2nd figure i will use the command **php artisan migrate:generate**

![image](https://github.com/user-attachments/assets/093b774b-e844-4e64-ae8a-52a90b4118d2)

I am not sure what you meant by _'Upon my checking, it appears that the SQL originates from the Laravel framework itself.'_

**Comment by kitloong** [comment]
> I am not sure what you meant by 'Upon my checking, it appears that the SQL originates from the Laravel framework itself.'

The SQL shown in your screenshot is generated by Laravel's built-in compileIndexes method, which retrieves a table's indexes. The generator relies on this method to obtain the indexes. 

If your database encounters an error when this method is called, there's not much I can do.
