### ISSUE TITLE
Incremental changes

### ISSUE THREAD

**Issue by GamerClassN7** [kitloong/laravel-migrations-generator#26]
is there any way how to generate incremental changes only ?

**Comment by kitloong** [comment]
Hello @GamerClassN7 

I am sorry for my very late reply. Currently, there is no way to generate incremental change.

The main use case of this generator is to provide a solution to generate migrations from the existing database.
Once you have started using migration, you should always make database changes through migration files by
```
php artisan make:migration
```
and migrate through
```
php artisan migrate
```

I will close this issue for now. 
But I am looking forward to furthering input of the implementation, a pull request is always welcome!

**Comment by XedinUnknown** [comment]
I would very much like to have the ability to generate migrations for incremental changes! When I publish my service, the backend that powers it can no longer be simply provisioned from scratch on every deployment: that would wipe exising users' data. This means that any further changes (including removal of fields or entire tables) must be done via migrations that run on top of the existing schema, i.e. incremental. Your tool has been incredibly useful to me in the development of a prototype, but without this ability I'm not sure how I could use it past that stage. Yet I need to use if very much.

Let's discuss a strategy, @kitloong. Would you like me to open a new issue, and outline the approach there?

**Comment by kitloong** [comment]
@XedinUnknown I am very sorry for late reply. Let's create a new issue and discuss approach from there!
