### ISSUE TITLE
FATAL erreur lors de l'installation sur LARAVEL 8

### ISSUE THREAD

**Issue by fderobien** [kitloong/laravel-migrations-generator#31]
bonjour, lorsque je mets la commande php artisan migrate:generate voici l'erreur affichée (ci-dessous). pouvez vous m'aider ?
de plus dans bootstrap/app.php $app->withFacades(); n'est pas accepté !

Fatal error: Uncaught ReflectionException: Class config does not exist in C:\wampServer64\www\LARAVEL\FdR_TP1_Laravelinititaion\TPJqueryDatatable\vendor\laravel\framework\src\Illumin
ate\Container\Container.php:830
Stack trace:
#0 C:\wampServer64\www\LARAVEL\FdR_TP1_Laravelinititaion\TPJqueryDatatable\vendor\laravel\framework\src\Illuminate\Container\Container.php(830): ReflectionClass->__construct('config'
)
#1 C:\wampServer64\www\LARAVEL\FdR_TP1_Laravelinititaion\TPJqueryDatatable\vendor\laravel\framework\src\Illuminate\Container\Container.php(712): Illuminate\Container\Container->build
('config')
#2 C:\wampServer64\www\LARAVEL\FdR_TP1_Laravelinititaion\TPJqueryDatatable\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(826): Illuminate\Container\Container->re
solve('config', Array, true)
#3 C:\wampServer64\www\LARAVEL\FdR_TP1_Laravelinititaion\TPJqueryDatatable\vendor\laravel\framework\src\Illuminate\Container\Container.php(651): Illuminate\Foundation\Application->re
solve('config', Array)
#4 C:\wampServer6 in C:\wampServer64\www\LARAVEL\FdR_TP1_Laravelinititaion\TPJqueryDatatable\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 832

**Comment by fderobien** [comment]
en enlevant l'ajout de la ligne $app->register(\KitLoong\MigrationsGenerator\MigrationsGeneratorServiceProvider::class); dans config/app.php 
=> c'est à présent opérationnel 
Désolée pour le dérangement !

**Comment by kitloong** [comment]
Hello @fderobien 

I am sorry, so the issue has been resolved?
