### ISSUE TITLE
Path is not working

### ISSUE THREAD

**Issue by akatche** [kitloong/laravel-migrations-generator#32]
Hi, first of all I want to thank you for this awesame package!! 

I have a small issue when running a command with the --path option and it always throws the following error:
```
php artisan migrate:generate --path="testing"

 ErrorException 

  file_put_contents(./testing/2021_02_10_170030_create_accion_comparables_table.php): failed to open stream: No such file or directory

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:135


```
My goal is to create the migrations on a different folder than migrations, it can be a subfolder as well, do you know if i´m doing something wrong?

Thanks in advance,
Alejandro

**Comment by didikz** [comment]
you should more use specific path, then try run

```
php artisan migrate:generate --path=database/migrations/generated
```

Generated files will be placed under `database/migrations/generated` directory
