### ISSUE TITLE
MySQLRepository uppercase property error

### ISSUE THREAD

**Issue by rcoves** [kitloong/laravel-migrations-generator#34]
Hello,
while trying to generate migrations i got an error

`Undefined property: stdClass::$Type at D:\Dev\wikitaf\vendor\kitloong\laravel-migrations generator\src\KitLoong\MigrationsGenerator\Repositories\MySQLRepository.php:22
`

The problem seems to be the `Type` property on `MySQLRepository::getSetPresetValues` and `MySQLRepository::getEnumPresetValues`

Replacing by `type` (without uppercase) works fine for me.

package version : "^4.4",

![image](https://user-images.githubusercontent.com/42941193/110964975-0dfb5a00-8354-11eb-8874-41b6046d2d95.png)

**Comment by kitloong** [comment]
Sorry for my late reply.
It seems in the column should be uppercase `Type` as stated in the official doc
https://dev.mysql.com/doc/refman/8.0/en/show-columns.html

Could you also provide your MySQL version?
