### ISSUE TITLE
Not working on laravel 8.27.0

### ISSUE THREAD

**Issue by Estebanrg21** [kitloong/laravel-migrations-generator#35]
First, following the installation steps, at the bootstrap/app.php there isn't a line that has _**$app->withFacades();**_ commented.
If I add _**$app->withFacades();**_ it shows up an error, so if I only add _**$app->register(\KitLoong\MigrationsGenerator\MigrationsGeneratorServiceProvider::class);**_ this error shows up:
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in path/to/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:830

**Comment by falsovsky** [comment]
By **reading** the documentation that only applies to Lumen, not Laravel.

**Comment by Estebanrg21** [comment]
My bad
