### ISSUE TITLE
Question, how to change the mapping  array of integers to  text?

### ISSUE THREAD

**Issue by thavarajansmi** [kitloong/laravel-migrations-generator#37]
Thanks for the package and keep it maintained
In postgres sql, currently array of integer is mapped to integer, 
may i know why it was mapped to integer, even if it's updated to text it was fine, but why as integer? any particular reason for that, 
though if i want to change the mapping to text how could i do that? any config changes need to applied

**Comment by kitloong** [comment]
Hi @thavarajansmi 

I am sorry I am not familiar with postgres sql.
Could you provide morre information such as detailed type field so that I can reproduce and look into it?

**Comment by thavarajansmi** [comment]
i hope this will provide some help 

https://www.db-fiddle.com/f/cuN63j7d25voMK9mWfJFU3/0


after digging little deep i found that this line need to be updated as text
 
https://github.com/kitloong/laravel-migrations-generator/blob/764a304216fbde1a2ed6645fb871105b884cfe54/src/KitLoong/MigrationsGenerator/Generators/SchemaGenerator.php#L121
