### ISSUE TITLE
where is generated files?

### ISSUE THREAD

**Issue by MahdiPishguy** [kitloong/laravel-migrations-generator#38]
after using the generating command i can't see them into `migrations` folder. where are them?

```
root@8680ab6ed9cd:/var/www# php artisan migrate:generate
Using connection: mysql

Generating migrations for: 

 Do you want to log these migrations in the migrations table? [Y/n] :
 > n

Setting up Tables and Index Migrations

Setting up Foreign Key Migrations


Finished!
```

`migrations` folder is empty. database connection and my `.env` file is correct because i'm using that now

**Comment by kitloong** [comment]
@MahdiPishguy 
I have tested with fresh Laravel installation but failed to reproduce your issue.
Migration files should be generated in path `./database/migrations`.

Please confirm and provide more info such as version number for debug purpose, or close this issue if the issue has been resolved.

**Comment by letture** [comment]
I have the same problem，environment is docker 、 laravel8.5、mysql8.0

**Comment by letture** [comment]
> @MahdiPishguy
> I have tested with fresh Laravel installation but failed to reproduce your issue.
> Migration files should be generated in path `./database/migrations`.
> 
> Please confirm and provide more info such as version number for debug purpose, or close this issue if the issue has been resolved.

This is the database has no tables, it should give a hint

**Comment by letture** [comment]
> @MahdiPishguy
> I have tested with fresh Laravel installation but failed to reproduce your issue.
> Migration files should be generated in path `./database/migrations`.
> 
> Please confirm and provide more info such as version number for debug purpose, or close this issue if the issue has been resolved.

This is the database has no tables, it should give a hint
