### ISSUE TITLE
Timestamp like `created_at` with default value `now()` generated with actual (fixed) timeasamp as a default value

### ISSUE THREAD

**Issue by AntonTalalaev** [kitloong/laravel-migrations-generator#39]
DB: postgres

Existing table structure:
    Column   |                    Type                          | Collation | Nullable |                          Default                          
----------------|--------------------------------------------|------------|-----------|-----------------------------------------------------------
created_at   | timestamp(0) without time zone  |                | not null  |  now()
updated_at  | timestamp(0) without time zone  |                | not null  |  now()

Generated table structure:
    Column   |                    Type                          | Collation | Nullable |                          Default                          
----------------|--------------------------------------------|------------|-----------|-----------------------------------------------------------
created_at   | timestamp(0) without time zone   |                | not null | '2021-06-21 19:30:05.997451'::timestamp without time zone
updated_at  | timestamp(0) without time zone   |                | not null | '2021-06-21 19:30:05.997451'::timestamp without time zone

Generated migration:
```
Schema::create('tabkeName', function (Blueprint $table) {
            $table->timestamp('created_at')->default('now()');
            $table->timestamp('updated_at')->default('now()');
        });
```

**Comment by kitloong** [comment]
Hello @AntonTalalaev 

Thank you for reporting this issue.

I understand this is the actual behaviour:
```
Schema::create('tabkeName', function (Blueprint $table) {
            $table->timestamp('created_at')->default('now()');
            $table->timestamp('updated_at')->default('now()');
        });
```

What is the **expected behavior**?
Is it supported by any method mentioned in the doc?
https://laravel.com/docs/8.x/migrations#introduction

**Comment by AntonTalalaev** [comment]
Hello @kitloong 

I fixed generated migration this way:
```
Schema::create('tabkeName', function (Blueprint $table) {
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
```

This result I got:
    Column   |                    Type                          | Collation | Nullable |                          Default                          
----------------|--------------------------------------------|------------|-----------|-----------------------------------------------------------
created_at   | timestamp(0) without time zone  |                | not null  |  CURRENT_TIMESTAMP
updated_at  | timestamp(0) without time zone  |                | not null  |  CURRENT_TIMESTAMP


Laravel also provide  `$table->timestamp('updated_at')->useCurrentOnUpdate()` but, as I understood, it doesn't support Postgres, only MySQL:
```
namespace Illuminate\Database\Schema;

use Illuminate\Support\Fluent;

/**
 * @method $this after(string $column) Place the column "after" another column (MySQL)
 * @method $this always() Used as a modifier for generatedAs() (PostgreSQL)
 * @method $this autoIncrement() Set INTEGER columns as auto-increment (primary key)
 * @method $this change() Change the column
 * @method $this charset(string $charset) Specify a character set for the column (MySQL)
 * @method $this collation(string $collation) Specify a collation for the column (MySQL/PostgreSQL/SQL Server)
 * @method $this comment(string $comment) Add a comment to the column (MySQL/PostgreSQL)
 * @method $this default(mixed $value) Specify a "default" value for the column
 * @method $this first() Place the column "first" in the table (MySQL)
 * @method $this generatedAs(string|Expression $expression = null) Create a SQL compliant identity column (PostgreSQL)
 * @method $this index(string $indexName = null) Add an index
 * @method $this nullable(bool $value = true) Allow NULL values to be inserted into the column
 * @method $this persisted() Mark the computed generated column as persistent (SQL Server)
 * @method $this primary() Add a primary index
 * @method $this spatialIndex() Add a spatial index
 * @method $this startingValue(int $startingValue) Set the starting value of an auto-incrementing field (MySQL/PostgreSQL)
 * @method $this storedAs(string $expression) Create a stored generated column (MySQL/PostgreSQL/SQLite)
 * @method $this type(string $type) Specify a type for the column
 * @method $this unique(string $indexName = null) Add a unique index
 * @method $this unsigned() Set the INTEGER column as UNSIGNED (MySQL)
 * @method $this useCurrent() Set the TIMESTAMP column to use CURRENT_TIMESTAMP as default value
 * @method $this useCurrentOnUpdate() Set the TIMESTAMP column to use CURRENT_TIMESTAMP when updating (MySQL)
 * @method $this virtualAs(string $expression) Create a virtual generated column (MySQL/PostgreSQL/SQLite)
 */
class ColumnDefinition extends Fluent
{
    //
}
```
