### ISSUE TITLE
column pgc.consrc does not exist | postgresql version 13

### ISSUE THREAD

**Issue by sohag1426** [kitloong/laravel-migrations-generator#44]
Illuminate\Database\QueryException

  SQLSTATE[42703]: Undefined column: 7 ERROR:  column pgc.consrc does not exist
LINE 7:                        pgc.consrc AS definition
                               ^
HINT:  Perhaps you meant to reference the column "pgc.conkey" or the column "pgc.conbin". (SQL:
                SELECT pgc.conname AS constraint_name,
                       pgc.contype,
                       ccu.table_schema AS table_schema,
                       ccu.table_name,
                       ccu.column_name,
                       pgc.consrc AS definition
                FROM pg_constraint pgc
                JOIN pg_namespace nsp ON nsp.oid = pgc.connamespace
                JOIN pg_class  cls ON pgc.conrelid = cls.oid
                LEFT JOIN information_schema.constraint_column_usage ccu
                          ON pgc.conname = ccu.constraint_name
                          AND nsp.nspname = ccu.constraint_schema
                WHERE contype ='c'
                    AND ccu.table_name='pgsql_radreplies'
                    AND ccu.column_name='username';
            )

**Comment by kitloong** [comment]
Possible solution https://github.com/jOOQ/jOOQ/issues/9331

**Comment by kitloong** [comment]
Hello @sohag1426 

Thank you for your report. I have investigated the issue and found a similar fix by JOOQ as mentioned in the previous comment.
`pg_get_constraintdef()` is a better option to get constraint definition.
I have published the fix with tag `v4.5.1`

I am closing this issue for resolution.
