### ISSUE TITLE
lumen Usage problem

### ISSUE THREAD

**Issue by wzy-wangge** [kitloong/laravel-migrations-generator#5]
How do I register for the service? Not for direct use

**Comment by kitloong** [comment]
Hello, this package is focused on Laravel development. I haven't test for Lumen yet but it is good to have Lumen supported.
Please let me test with Lumen and I will update my result here

**Comment by wzy-wangge** [comment]
thank you,I will recommend it to my friends

**Comment by kitloong** [comment]
Lumen: https://github.com/kitloong/laravel-migrations-generator#lumen-setup
