### ISSUE TITLE
Procedure support

### ISSUE THREAD

**Issue by hhuseyincihangir** [kitloong/laravel-migrations-generator#63]
Can procedure support be added? I am sure it will make the project much more useful.

**Comment by genisaretskiy** [comment]
hello, any updates with procedure/functions for posgresql ?

**Comment by kitloong** [comment]
Hi @genisaretskiy , thanks for asking.

I am currently working on this feature. While I still do not have a precise date yet, most likely, I will be able to release this feature by this month.

**Comment by kitloong** [comment]
Sorry for the long wait, released with tag `v6.5.0`
