### ISSUE TITLE
Need the support of enum / custom type

### ISSUE THREAD

**Issue by partharajbd** [kitloong/laravel-migrations-generator#65]
Database connection: **pgsql**

In the following scenario- 

```
create type my_status as enum ('PENDING', 'ACTIVE', 'SUSPENDED');
```

```
create table mydb.mytable
(
	...
	status my_status not null,
	...
);
```
getting the following exception-

> Unknown database type my_status requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.
> ~\vendor\doctrine\dbal\src\Platforms\AbstractPlatform.php:394

**Comment by kitloong** [comment]
Released with tag `v6.4.0`
