### ISSUE TITLE
When you delete now, the table automatically carries the prefix

### ISSUE THREAD

**Issue by wzy-wangge** [kitloong/laravel-migrations-generator#7]
![image](https://user-images.githubusercontent.com/31752332/78734240-4a6f4a80-797a-11ea-81c6-ce6536df6901.png)
#### The following modifications are recommended
![image](https://user-images.githubusercontent.com/31752332/78734196-31ff3000-797a-11ea-8f09-422d2c5a611b.png)

**Comment by wzy-wangge** [comment]
### I don't know why the books can't be uploaded
>The main reason is that the 'down' method will automatically generate the table name with the table prefix, and then add the table prefix when rolling back

**Comment by kitloong** [comment]
Hello, I think this issue has been fixed in current version
Commit: b4f51d8

Could you check?
