### ISSUE TITLE
 Return value of MigrationsGenerator\MigrationsGeneratorSetting::getTableFilename() must be of the type string, null returned

### ISSUE THREAD

**Issue by EXEIdeas** [kitloong/laravel-migrations-generator#73]
I am having the upper mentioned error even after trying multiple time but still it is not working. Anyway, here is the steps I followed and got this error.

- Laravel: 5.8.38
- NPM: 6.4.1
- NODE: 10.15.3
- [composer.json](https://textdoc.co/Ky9Ui3ngVcRrOeqm) File

First I run this command line.
`composer require --dev "kitloong/laravel-migrations-generator"`

Then edit app.php file and added the below code to register this.
```
'providers' => [
    ..................
    \MigrationsGenerator\MigrationsGeneratorServiceProvider::class,
  ],
```

Then run the below code as I have many connections to different database in my database.php. MY localhost connection is labeled as localhost also as I want to generate migrations for my localhost database tables only.
`php artisan migrate:generate --connection="localhost"`

Now after doing all above, I got the below error...
```
$ php artisan migrate:generate --connection="localhost"
In MigrationsGeneratorSetting.php line 225:
Return value of MigrationsGenerator\MigrationsGeneratorSetting::getTableFilename() must be of the type string, null returned
```

**Comment by kitloong** [comment]
Hi @EXEIdeas 

Thank you for reporting. 
The attached composer.json is not reachable, could you please share the composer content?

Could you also please provide the generator version you are using? In case you are not, you should use '5.x' as it is latest version and compatible with old Laravel version.

**Comment by kitloong** [comment]
I am sorry, I am able to view `composer.json` now.
I tried the steps you have mentioned however I failed to reproduce the issue.

Here's my approach:
1. Download Laravel v5.8.
2. Replace with your `composer.json`
3. Reinstall.
4. Run generate command with connection name.

Please provide more information at your convenience for investigation purposes.
