### ISSUE TITLE
Feature Request: combine foreign keys migrations and create_table migrations

### ISSUE THREAD

**Issue by UltraCakeBakery** [kitloong/laravel-migrations-generator#82]
We have a lot of tables, each of which contain multiple foreign keys.
Right now this generator generates separate migrations for creating the table and adding keys. 

I want just one migration that fully creates the table.

**Comment by UltraCakeBakery** [comment]
Yeah never mind this one, I forgot those foreign key constraints need to be added in a separate run. My bad!

**Comment by kitloong** [comment]
Hi @UltraCakeBakery 

Thank you for your feedback.

Additionally, if too many migration files are your concern, you could squash all migrations into a single file by
```
php artisan migrate:generate --squash
```
