### ISSUE TITLE
Primary key column small bug 🤔

### ISSUE THREAD

**Issue by everstudybee** [kitloong/laravel-migrations-generator#92]
Hi, thanks for your work 👏

I think I found a little bug. It is about generating an entry for the column from the primary key. Currently, the following line is generated:
`$table-> integer ('Id', true);`

And according to the documentation https://laravel.com/docs/9.x/migrations#column-method-bigIncrements should be generated like this:
`$table  -> bigIncrements ('id');` or
`$table -> id();` in conjunction with this link https://laravel.com/docs/9.x/migrations#column-method-id

Thank you again for your work 👍

**Comment by kitloong** [comment]
Hi @everstudybee 

Thank you for reporting the issue.
Could you please provide which type of database you are using?
And it would be helpful if you could provide the create table statement.

**Comment by everstudybee** [comment]
Yes, database type... I use MariaDB and XAMPP

**Comment by kitloong** [comment]
How about your CREATE TABLE statement?
If the column is 

```
`id` int(11) NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
```

then `$table->integer('id', true);` is expected.

If the column is 

```
`id` bigint(11) UNSIGNED NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
```

* Notice the `UNSIGNED`

then `$table ->bigIncrements('id');` is expected.

**Comment by everstudybee** [comment]
Everything is correct and it works as you described. I just didn't take into account that my primary key was `int` and not `bigint`. You can mark as resolved. Thanks for the quick replies. 👍
